# Generated by Django 5.2.5 on 2025-08-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter price in USD', max_digits=8)),
                ('category', models.CharField(choices=[('EL', 'Electronics'), ('FD', 'Food'), ('CL', 'Clothes')], default='EL', max_length=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_until', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
            options={
                'ordering': ['-price'],
            },
        ),
    ]
